Repository openedx/frontend-app-learner-dashboard, pull requests merged in 2023-10, with the labels that each got.

#205 fix: get brand logo file path from env
  src/config/index.js
  src/containers/LearnerDashboardHeader/BrandLogo.jsx
  src/containers/LearnerDashboardHeader/__snapshots__/BrandLogo.test.jsx.snap
Labels: open-source-contribution, waiting for eng review

#220 chore: bump frontend-platform (#216)
  package-lock.json
  package.json
Labels: needs maintainer attention

#184 fix(deps): replace edx.org brand dependency with openedx brand (#183)
  package-lock.json
  package.json
Labels: waiting on author, open-source-contribution

#209 feat: babel-plugin-react-intl to babel-plugin-formatjs migration
  Makefile
  package-lock.json
  package.json
Labels: needs maintainer attention
