Repository openedx/frontend-app-learner-dashboard, pull requests merged in 2024-11, with the labels that each got.

#495 Remove unused dependencies #427
  package-lock.json
  package.json
  src/test/app.test.jsx
Labels: open-source-contribution

#490 chore: npm publish action removed
  .github/workflows/npm-publish.yml
  .releaserc
  package-lock.json
  package.json
Labels: open-source-contribution

#479 fix: display programs only if the url is configured
  src/containers/LearnerDashboardHeader/LearnerDashboardMenu.jsx
  src/containers/LearnerDashboardHeader/__snapshots__/index.test.jsx.snap
  src/containers/LearnerDashboardHeader/hooks.js
  src/containers/LearnerDashboardHeader/hooks.test.js
  src/containers/LearnerDashboardHeader/index.test.jsx
  src/data/services/lms/api.js
  src/data/services/lms/urls.js
  src/hooks/api.js
  src/hooks/api.test.js
Labels: open-source-contribution, core contributor, waiting for eng review

#498 fix: added LMS_BASE_URL for brand logo
  src/containers/LearnerDashboardHeader/BrandLogo.jsx
  src/containers/LearnerDashboardHeader/BrandLogo.test.jsx
  src/containers/LearnerDashboardHeader/__snapshots__/BrandLogo.test.jsx.snap
Labels: open-source-contribution, waiting for eng review, create-sandbox
