Repository openedx/frontend-app-learner-dashboard, pull requests merged in 2024-02, with the labels that each got.

#280 feat: tutor-mfe compatiblilty for `atlas pull` | FC-0012
  Makefile
  package-lock.json
  package.json
Labels: open-source-contribution, core contributor

#273 fix: URLs get the current value of LMS_BASE_URL from getConfig() #269
  src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
  src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
  src/containers/LearnerDashboardHeader/ExpandedHeader/index.test.jsx
  src/data/services/lms/api.js
  src/data/services/lms/api.test.js
  src/data/services/lms/urls.js
Labels: open-source-contribution

#284 fix: URLs get the current value of LMS_BASE_URL from getConfig()
  src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
  src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
  src/containers/LearnerDashboardHeader/ExpandedHeader/index.test.jsx
  src/data/services/lms/api.js
  src/data/services/lms/api.test.js
  src/data/services/lms/urls.js
Labels: open-source-contribution, core contributor, waiting for eng review

#293 fix: #287 translation strigs are not exported
  src/components/ZendeskFab/messages.js
  src/containers/CourseCard/components/CourseCardActions/messages.js
  src/containers/CourseCard/components/CourseCardBanners/CreditBanner/messages.js
  src/containers/CourseCard/components/CourseCardBanners/CreditBanner/views/messages.js
  src/containers/CourseCard/components/CourseCardBanners/RelatedProgramsBanner/messages.js
  src/containers/CourseCard/components/CourseCardBanners/messages.js
  src/containers/CourseCard/components/CourseCardDetails/messages.js
  src/containers/CourseCard/components/CourseCardMenu/SocialShareMenu.test.jsx
  src/containers/CourseCard/components/CourseCardMenu/index.test.jsx
  src/containers/CourseCard/components/CourseCardMenu/messages.js
  src/containers/CourseCard/messages.js
  src/containers/EmailSettingsModal/messages.js
  src/containers/RelatedProgramsModal/messages.js
  src/containers/SelectSessionModal/messages.js
  src/containers/UnenrollConfirmModal/components/messages.js
  src/messages.js
Labels: open-source-contribution, core contributor, needs maintainer attention

#292 refactor: remove painted door recommendations experiment
  .env
  .env.test
  src/containers/LearnerDashboardHeader/CollapsedHeader/CollapseMenuBody.jsx
  src/containers/LearnerDashboardHeader/CollapsedHeader/__snapshots__/CollapseMenuBody.test.jsx.snap
  src/containers/LearnerDashboardHeader/ExpandedHeader/__snapshots__/index.test.jsx.snap
  src/containers/LearnerDashboardHeader/ExpandedHeader/index.jsx
  src/containers/WidgetContainers/AppWrapper/__snapshots__/index.test.jsx.snap
  src/containers/WidgetContainers/AppWrapper/index.jsx
  src/containers/WidgetContainers/AppWrapper/index.test.jsx
  src/containers/WidgetContainers/WidgetNavbar/__snapshots__/index.test.jsx.snap
  src/containers/WidgetContainers/WidgetNavbar/index.jsx
  src/containers/WidgetContainers/WidgetNavbar/index.test.jsx
  src/widgets/RecommendationsPaintedDoorBtn/PaintedDoorExperimentContext.jsx
  src/widgets/RecommendationsPaintedDoorBtn/PaintedDoorExperimentContext.test.jsx
  src/widgets/RecommendationsPaintedDoorBtn/__snapshots__/index.test.jsx.snap
  src/widgets/RecommendationsPaintedDoorBtn/components/NavbarButton.jsx
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/__snapshots__/index.test.jsx.snap
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/hooks.js
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/hooks.test.js
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/index.jsx
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/index.scss
  src/widgets/RecommendationsPaintedDoorBtn/components/PaintedDoorModal/index.test.jsx
  src/widgets/RecommendationsPaintedDoorBtn/components/RecommendationsPanelButton.jsx
  src/widgets/RecommendationsPaintedDoorBtn/constants.js
  src/widgets/RecommendationsPaintedDoorBtn/index.jsx
  src/widgets/RecommendationsPaintedDoorBtn/index.test.jsx
  src/widgets/RecommendationsPaintedDoorBtn/messages.js
  src/widgets/RecommendationsPaintedDoorBtn/track.js
  src/widgets/RecommendationsPaintedDoorBtn/track.test.js
  src/widgets/RecommendationsPanel/LoadedView.jsx
  src/widgets/RecommendationsPanel/LoadedView.test.jsx
  src/widgets/RecommendationsPanel/__snapshots__/LoadedView.test.jsx.snap
  src/widgets/RecommendationsPanel/index.jsx
  src/widgets/RecommendationsPanel/index.test.jsx
Labels: waiting for eng review, needs maintainer attention
