Repository openedx/frontend-app-learner-dashboard, pull requests merged in 2025-05, with the labels that each got.

#569 feat: support design tokens and paragon 23
  .env
  .env.development
  .env.test
  package-lock.json
  package.json
  src/App.scss
  src/containers/CourseCard/CourseCard.scss
  src/containers/CourseCard/components/CourseCardDetails/index.scss
  src/containers/CoursesPanel/NoCoursesView/index.scss
  src/containers/CoursesPanel/index.scss
  src/containers/Dashboard/index.scss
  src/containers/MasqueradeBar/index.scss
Labels: waiting on author, open-source-contribution, core contributor, create-sandbox

#613 Replace use of query-string dependency for URLSearchParams #571
  package-lock.json
  package.json
  src/containers/CoursesPanel/hooks.js
  src/containers/CoursesPanel/hooks.test.js
  src/data/services/lms/utils.js
  src/data/services/lms/utils.test.js
  webpack.dev.config.js
  webpack.prod.config.js
Labels: open-source-contribution, mao-onboarding

#614 Cleanup learnerDashboardHeader files
  src/containers/LearnerDashboardHeader/BrandLogo.jsx
  src/containers/LearnerDashboardHeader/BrandLogo.test.jsx
  src/containers/LearnerDashboardHeader/__snapshots__/BrandLogo.test.jsx.snap
  src/containers/LearnerDashboardHeader/hooks.js
  src/containers/LearnerDashboardHeader/hooks.test.js
  src/data/redux/requests/reducer.test.js
Labels: open-source-contribution, waiting for eng review, mao-onboarding

#612 fix: add missing translation for notices not found
  src/components/NoticesWrapper/api.js
  src/components/NoticesWrapper/hooks.js
  src/components/NoticesWrapper/hooks.test.js
Labels: open-source-contribution

#618 Audit usage of header elements in Learner Dashboard
  src/containers/CoursesPanel/NoCoursesView/__snapshots__/index.test.jsx.snap
  src/containers/CoursesPanel/NoCoursesView/index.jsx
  src/containers/Dashboard/DashboardLayout.jsx
  src/containers/Dashboard/DashboardLayout.test.jsx
  src/containers/Dashboard/__snapshots__/DashboardLayout.test.jsx.snap
  src/containers/Dashboard/index.scss
  src/containers/LearnerDashboardHeader/ConfirmEmailBanner/__snapshots__/index.test.jsx.snap
  src/containers/LearnerDashboardHeader/ConfirmEmailBanner/index.jsx
Labels: open-source-contribution, mao-onboarding

#619 Add advertised start date on course card
  src/containers/CourseCard/components/CourseCardDetails/hooks.js
  src/data/redux/app/selectors/courseCard.js
  src/data/redux/app/selectors/courseCard.test.js
Labels: open-source-contribution, waiting for eng review, mao-onboarding
